name: Deploy Firebase Functions
on:
    push:
        branches:
            - master
jobs:
    main:
        name: Deploy to Firebase
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: jsryudev/deploy-firebase-functions@v20.0.0
              env:
                  FIREBASE_TOKEN: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_QRCODE_REST_API }}
                  FIREBASE_PROJECT: qrcode-rest-api
